name: Rust

on:
  push:
    branches: [ "feature/actions" ]
  pull_request:
    branches: [ "feature/actions" ]

defaults:
  run:
    shell: bash
    working-directory: parse_md

env:
  CARGO_TERM_COLOR: always
  RUST_PROJECT_NAME: parse_md

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Dump GitHub context
      run: echo '${{ toJSON(github) }}'
    - name: Get Markdown files for this push
      run: |
        # 拡張子が.mdのファイルを取得し、commit.txtに出力
        git show ${{ github.event.head_commit.id }} --format= --name-status | grep -i .md$ || true > ${{ github.workspace }}/commit.txt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run rust project
      run: ./target/debug/${{ env.RUST_PROJECT_NAME }}
      env:
        COMMIT_INFO_PATH: ${{ github.workspace }}/commit.txt
        TIMESTAMP: ${{ github.event.head_commit.timestamp }}
        WORKSPACE: ${{ github.workspace }}
    
