name: Rust

on:
  push:
    branches: [ "feature/actions" ]
  pull_request:
    branches: [ "feature/actions" ]

defaults:
  run:
    shell: bash
    working-directory: parse_md

env:
  CARGO_TERM_COLOR: always
  RUST_PROJECT_NAME: parse_md

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Dump GitHub context
      run: echo '${{ toJSON(github) }}'
    - name: Get HEAD commit date & files
      run: |
        git show --format=%cd --name-status > commit_info.txt
        git show ${{ github.event.head_commit.id }} --format= --name-status > commit_info.txt
        git show ${{ github.event.head_commit.id }} --format= --name-status
        ls 
        pwd
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run rust project
      run: ./target/debug/${{ env.RUST_PROJECT_NAME }}
      env:
        COMMIT_INFO_PATH: commit_info.txt
        TIME_STAMP: ${{ github.event.head_commit.timestamp }}
    
