on:
  push

defaults:
  run:
    shell: bash
    working-directory: parse_md

env:
  CARGO_TERM_COLOR: always
  RUST_PROJECT_NAME: parse_md

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get HEAD commit date & files
      run: |
        git show --format=%cd --name-status > commit_info.txt
        ls 
        pwd
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run rust project
      run: ./target/debug/${{ env.RUST_PROJECT_NAME }}
      env:
        COMMIT_INFO_PATH: commit_info.txt
    